#!/usr/bin/env bash
# writing a script that displays the content of a specific file that displays username user id and home directory path with a while loop
fcontent="etc/passwd"
while read -r fline
do
	cut -d: -f 1,3,6 "$fline"
done < $fcontent
