#!/usr/bin/env bash
#Write a script that displays 5 different fields in a story with a file loop
fcontent="/etc/passwd"
#lpscode="x"
while IFS= read -r fline
do
	luser=$(echo "$fline" | cut -d: -f 1)
	lgang=$(echo "$fline" | cut -d: -f 4)
	ldir=$(echo "$fline" | cut -d: -f 6)
	lrides=$(echo "$fline" | cut -d: -f 7)
	lplace=$(echo "$fline" | cut -d: -f 3)
	lpscode=$(echo "$fline" | cut -d: -f 2)
	lmoinfo=$(echo "$fline" | cut -d: -f 5)
	echo "the user $luser is part of the $lgang gang, lives in $ldir and rides $lrides. $lplace's place is protected by the passcode $lpscodemm more info about the user here: $lmoinfo"
done < $fcontent
