#!/usr/bin/env bash
# creates a while loop that has different outputs with if statements.
i=1
while [ $i -le 10 ];
do
	i=$(( i+1 ))
	if [[ $i = 5 ]];
	then echo "bad luck";
	elif [[ $i = 9 ]]; then
	echo "good luck";
	else echo "Best School"; 
	fi
done
