#!/usr/bin/env bash
#use a while loop to count up to 20 with a bunch of cases.
i=1
while [ $i -le 20 ];
do
	case $i in
		4) echo "4"
		   echo "bad luck from China"
	   	;;
     		5) echo "9"
		   echo "bad luck from Japan"
   		;;
		17) echo "17"
		    echo "bad luck from Italy"
    		;;		    
		$1) echo "$i"
		;;
	esac
	i=$(( i + 1 ))
done
