#!/usr/bin/env bash
#creating a script that lists hours and minutes like a digital clock
i=0
h=0
while [ $h -le 12 ];
do
	echo "Hour: $h"
	while [ $i -le 59 ]
		do
		echo $i
		i=$(( i+1 ))
		done
	i=1
	h=$(( h+1 ))
done
