#!/usr/bin/env bash
#creating a script that lists hours and minutes like a digital clock
i=1
while [ $i -le 60 ];
do
	echo "Hour: 0"
	i=$(( i+1 ))
	if [[ $i = 0 ]];
	then echo "Hour: 0";
	elif [[ $i = 60 ]]; then
	echo "Hour: 1";
	else echo "$i"; 
	fi
done
